--INSERT into user (username, password, role)
--values ('user', 'pass', 'ROLE_USER');
--
--INSERT into user (username, password, role)
--values ('admin', 'pass', 'ROLE_ADMIN');
--
--INSERT into authorities (username, authority)
--values ('user', 'ROLE_USER');
--
--INSERT into authorities (username, authority)
--values ('admin', 'ROLE_ADMIN');